const palavras = {
    "Objeto": ["Adaptador", "Aerofólio", "Agulheiro", "Amaciante", "Ampulheta", "Aquecedor", "Armadilha", "Assadeira", "Bafômetro", "Bagageiro", "Balaclava", "Balaústre", "Batedeira", "Betoneira", "Bomba de ar", "Bracelete", "Brinquedo", "Cabideiro", "Caderneta", "Cafeteira", "Caldeirão", "Candeeiro", "Caneleira", "Carrilhão", "Cassetete", "Catapulta", "Catavento", "Clarinete", "Comedouro", "Corretivo", "Crucifixo", "Espanador", "Ferradura", "Ferrorama", "Figurinha", "Filmadora", "Fiodental", "Furadeira", "Geladeira", "Giz de cera", "Gramofone", "Guirlanda", "Interfone", "Joelheira", "Lamparina", "Lancheira", "Lapiseira", "Luminária", "Mamadeira", "Mangueira", "Marionete", "Meia calça", "Microfone", "Minissaia", "Paliteiro", "Parabrisa", "Pé de cabra", "Podadeira", "Poncheira", "Queijeira", "Ralo de pia", "Reco-reco", "Relicário", "Repelente", "Sabão em pó", "Saladeira", "Salto alto", "Sapateira", "Sapatilha", "Sombrinha", "Tabuleiro", "Televisão", "Trampolim", "Triângulo", "Vídeo game", ],
    "Cantor": ["Lucas Lucco", "Alcione","Rita Lee", "Alceu Valença","Cavetown","Lana del Rey","Kamaitachi"],
    "Banda": ["Coldplay", "System of a Down","Metallica"],
    "Lugar": ["Parque", "Fazenda", "Shopping", "Quadra de Futebol"],
    "Comida": ["Abobrinha", "Alcaparra", "Alho-poró", "Almôndega", "Arroz doce", "Berinjela", "Beterraba", "Brevidade", "Cajamanga", "Cajuzinho", "Calabresa", "Camu-camu", "Capuccino", "Carambola", "Casadinho", "Casquinha", "Cebolinha", "Champanhe", "Chantilly", "Chimarrão", "Chocolate", "Chocotone", "Churrasco", "Erva-doce", "Espetinho", "Espinafre", "Framboesa", "Fruta-pão", "Grumixama", "Leite em pó", "Macadâmia", "Malagueta", "Margarina", "Maria mole", "Marmelada", "Maçã verde", "Milk shake", "Molho rosé", "Mortadela", "Mussarela", "Nectarina", "Provolone", "Pão de alho", "Requeijão", "Rocambole", "Rosquinha", "Sal grosso", "Sanduíche", "Sarapatel", "Siriguela", "Suco de uva", "Tamarindo", "Tangerina", "Vinagrete", ],
    "Animal": ["Água-viva", "Andorinha", "Barbatana", "Bem-te-vi", "Bicho-pau", "Borboleta", "Cachalote", "Calopsita", "Carrapato", "Chimpanzé", "Chinchila", "Crocodilo", "Curimbatá", "Escorpião", "Gafanhoto", "Jacutinga", "Lagartixa", "Nadadeira", "Peixe-boi", "Peixe-lua", "Peixe-rei", "Peixe-sol", "Percevejo", "Periquito", "Tamanduaí", "Tartaruga", "Tarântula", "Tico-tico", "Urso panda", "Vaga-lume",],
    "Bebida": ["Suco de Morango","Tereré","Chimarrão","Refrigerante de guarana"],
    "Filme": ["Os Vingadores", "Capitão América", "O chamado","A Cabana","Bumblebee","Trasnformers","Homem aranha de volta ao lar"],
    "Série": ["Andy panda", "Arlequina", "Bananaman", "Barbapapa", "Betty boop", "Cebolinha", "Cyborg 009", "Death note", "Dom pixote", "Eek the cat", "Eufrazino", "Family guy", "Florzinha", "Gato félix", "Hey arnold", "Hortelino", "Kid vs. kat", "Lex luthor", "Lola bunny", "Luluzinha", "Mistureba", "Os jetsons", "Os oblongs", "Pepe legal", "Roy corrói", "Se liga ian", "South park", "Super sumô", "Super vaca", "Tico e teco", "Tom e jerry", "Tutubarão", "Wolverine", "Woodstock", "Yu-gi-oh!", "Zatch bell", "Zé carioca", "Zé colméia", "Zeca urubu","Mama cosma", ],
    
};